#!/usr/bin/env python3
"""
check_hysteresis.py - is the X->Y bulge direction-dependent?

Splits a straight-X sweep capture by travel direction (rx rising vs falling),
fits cY(rx) for each, and reports how far they diverge. If they diverge enough
that a memoryless LUT can't fix it, emits a DIRECTION-AWARE header (two LUTs,
selected at runtime by motion direction).

Usage: python3 check_hysteresis.py bulge.ndjson [src/stick_correction.h]
"""
import json, sys

DIVERGE_THRESH = 0.015      # normalized: above this, hysteresis is worth handling
DIR_DEADBAND   = 0.003      # ignore tiny rx wiggles when deciding direction

def load(path):
    pts=[]
    for line in open(path):
        line=line.strip()
        if not line: continue
        d=json.loads(line)
        if "rx" in d and "ry" in d:
            pts.append((float(d["rx"]), float(d["ry"])))
    return pts

def median(v):
    v=sorted(v); n=len(v)
    if n==0: return None
    return v[n//2] if n%2 else 0.5*(v[n//2-1]+v[n//2])

def fit_dir(pts, NX):
    step=2.0/(NX-1)
    bins={i:[] for i in range(NX)}
    for rx,ry in pts:
        i=max(0,min(NX-1,int(round((rx+1.0)/step))))
        bins[i].append(ry)
    cY=[median(bins[i]) for i in range(NX)]
    mid=(NX-1)//2
    for i in range(mid,NX): cY[i]=0.0
    cY[mid]=0.0
    known=[i for i in range(NX) if cY[i] is not None]
    for i in range(NX):
        if cY[i] is None:
            lo=max([k for k in known if k<i],default=known[0])
            hi=min([k for k in known if k>i],default=known[-1])
            cY[i]=cY[lo] if lo==hi else cY[lo]+(cY[hi]-cY[lo])*(i-lo)/(hi-lo)
    return cY

def main():
    path=sys.argv[1] if len(sys.argv)>1 else "bulge.ndjson"
    out =sys.argv[2] if len(sys.argv)>2 else "stick_correction.h"
    pts=load(path)
    NX=33; step=2.0/(NX-1)

    # classify by direction of travel (with deadband + carry-forward)
    rising=[]; falling=[]; d=-1
    for k in range(1,len(pts)):
        dx=pts[k][0]-pts[k-1][0]
        if   dx >  DIR_DEADBAND: d=+1
        elif dx < -DIR_DEADBAND: d=-1
        (rising if d>0 else falling).append(pts[k])

    cyR=fit_dir(rising, NX)   # rx increasing (returning toward center/right)
    cyF=fit_dir(falling,NX)   # rx decreasing (pushing further left)

    mid=(NX-1)//2
    maxdiv=0.0; argdiv=0.0
    print("="*64)
    print("  HYSTERESIS CHECK  (rx falling = push left, rising = return)")
    print("="*64)
    print(f"{len(pts)} pts -> {len(falling)} falling, {len(rising)} rising\n")
    print("  rx       push(falling)   return(rising)   |diff|")
    for i in range(0,mid+1):
        rx=-1.0+i*step; diff=cyF[i]-cyR[i]
        if abs(diff)>maxdiv: maxdiv=abs(diff); argdiv=rx
        print(f"  {rx:+.3f}    {cyF[i]:+.4f}        {cyR[i]:+.4f}       {abs(diff):.4f}")
    print(f"\n  max divergence {maxdiv:.4f} at rx={argdiv:+.3f}")

    if maxdiv < DIVERGE_THRESH:
        print(f"  -> below {DIVERGE_THRESH}: memoryless LUT is fine. Keep the single-LUT header.")
        return

    print(f"  -> above {DIVERGE_THRESH}: HYSTERESIS confirmed. Writing direction-aware header.")
    def emit_lut(name, arr):
        s=f"static const float {name}[RSC_NX] = {{\n  "
        for i,v in enumerate(arr):
            s+=f"{v:+.5f}f,"
            if i%8==7: s+="\n  "
        return s+"\n};\n\n"
    with open(out,"w") as h:
        h.write("// Auto-generated by check_hysteresis.py - direction-aware X->Y decouple\n")
        h.write("// Picks cY(rx) by travel direction to cancel hysteresis. Right stick only.\n")
        h.write("#pragma once\n#include <stdint.h>\n\n")
        h.write("#define ENABLE_RIGHT_STICK_CORRECTION 1\n")
        h.write("#define RSC_CENTER_X (976)\n#define RSC_CENTER_Y (-128)\n")
        h.write("#define RSC_TAPER 1.0f\n")
        h.write(f"#define RSC_NX {NX}\n")
        h.write(f"#define RSC_DIR_DEADBAND {int(DIR_DEADBAND*32767)}  // int16 rx step to flip direction\n\n")
        h.write(emit_lut("RSC_CY_FALL", cyF))   # pushing left
        h.write(emit_lut("RSC_CY_RISE", cyR))   # returning
        h.write(r"""
static inline int16_t rsc_clamp(float v){
    if (v >  32767.0f) return  32767;
    if (v < -32768.0f) return -32768;
    return (int16_t)(v >= 0 ? v + 0.5f : v - 0.5f);
}

// Direction-aware decouple. Static state is fine: one right stick, one caller.
static inline void correct_right_stick(int16_t *px, int16_t *py){
#if ENABLE_RIGHT_STICK_CORRECTION
    static int16_t last_x = 0;
    static int8_t  dir    = -1;          // -1 = pushing left (falling), +1 = returning

    int16_t xi = (int16_t)(*px - RSC_CENTER_X);
    int     dx = (int)xi - (int)last_x;
    if      (dx >  RSC_DIR_DEADBAND) dir = +1;
    else if (dx < -RSC_DIR_DEADBAND) dir = -1;   // else: hold previous dir
    last_x = xi;

    float x = (float)xi;
    float y = (float)(*py) - (float)RSC_CENTER_Y;

    float xn = x * (1.0f/32767.0f);
    if (xn < -1.0f) xn = -1.0f; else if (xn > 1.0f) xn = 1.0f;
    float u  = (xn + 1.0f) * 0.5f * (RSC_NX - 1);
    int   i0 = (int)u; if (i0 > RSC_NX-2) i0 = RSC_NX-2; if (i0 < 0) i0 = 0;
    float f  = u - (float)i0;

    const float *lut = (dir > 0) ? RSC_CY_RISE : RSC_CY_FALL;
    float cy = lut[i0]*(1.0f-f) + lut[i0+1]*f;

    y -= cy * 32767.0f * RSC_TAPER;

    *px = rsc_clamp(x);
    *py = rsc_clamp(y);
#else
    (void)px; (void)py;
#endif
}
""")
    print(f"  wrote {out}")

if __name__=="__main__":
    main()