#!/usr/bin/env python3
"""
fit_bulge.py - X->Y cross-coupling fitter for tusb_gamepad_xbox_to_xinput_pico

Capture: with r2p-reader --ndjson, push the RIGHT stick straight along X
(left and back, then right and back) several times, ry intended ~0 throughout.
The defect is X bleeding into Y; this measures cY(rx) = the Y bulge vs X and
emits a decoupling header so firmware does ry' = ry - cY(rx).

Usage: python3 fit_bulge.py bulge.ndjson [src/stick_correction.h]
"""
import json, math, sys

def load(path):
    pts=[]
    for line in open(path):
        line=line.strip()
        if not line: continue
        d=json.loads(line)
        if "rx" in d and "ry" in d:
            pts.append((float(d["rx"]), float(d["ry"])))
    return pts

def median(v):
    v=sorted(v); n=len(v)
    if n==0: return None
    return v[n//2] if n%2 else 0.5*(v[n//2-1]+v[n//2])

def main():
    path = sys.argv[1] if len(sys.argv)>1 else "bulge2.ndjson"
    out  = sys.argv[2] if len(sys.argv)>2 else "stick_correction.h"
    pts=load(path)

    NX=33                      # LUT entries over rx in [-1, 1]
    step=2.0/(NX-1)
    # bin by rx, take median ry per bin (systematic coupling, rejects wiggle)
    bins={i:[] for i in range(NX)}
    for rx,ry in pts:
        i=int(round((rx+1.0)/step))
        i=max(0,min(NX-1,i))
        bins[i].append(ry)
    cY=[None]*NX
    for i in range(NX):
        cY[i]=median(bins[i])
    # anchors: true center has no coupling; right half (rx>=0) is clean
    mid=(NX-1)//2
    cY[mid]=0.0
    for i in range(mid, NX): 
        if cY[i] is None: cY[i]=0.0
    # the captured straight-X sweep is the -X side; right side stays clean
    for i in range(mid+1, NX): cY[i]=0.0
    # fill any empty -X bins by linear interpolation between known anchors
    known=[i for i in range(NX) if cY[i] is not None]
    for i in range(NX):
        if cY[i] is None:
            lo=max([k for k in known if k<i], default=known[0])
            hi=min([k for k in known if k>i], default=known[-1])
            if lo==hi: cY[i]=cY[lo]
            else:
                t=(i-lo)/(hi-lo); cY[i]=cY[lo]*(1-t)+cY[hi]*t
    # light smoothing (3-tap) on the -X half only
    sm=cY[:]
    for i in range(1,mid):
        sm[i]=0.25*cY[i-1]+0.5*cY[i]+0.25*cY[i+1]
    cY=sm

    # report
    print("="*56)
    print("  X->Y CROSS-COUPLING FIT  (ry' = ry - cY(rx))")
    print("="*56)
    print(f"{len(pts)} points\n  rx       cY (Y bleed to subtract)")
    for i in range(0,mid+1):
        rx=-1.0+i*step
        bar="#"*int(abs(cY[i])*200)
        print(f"  {rx:+.3f}   {cY[i]:+.4f}  {bar}")
    peak=max(range(NX), key=lambda i:abs(cY[i]))
    print(f"\n  peak bleed {cY[peak]:+.4f} at rx={-1.0+peak*step:+.3f}")
    print("  (right half rx>=0 forced clean; inner -X region interpolated if")
    print("   your capture didn't cover it - run on the full sweep to fill it)")

    # emit header
    with open(out,"w") as h:
        h.write("// Auto-generated by fit_bulge.py - right-stick X->Y decoupling\n")
        h.write("// Cancels the cross-axis bulge: ry' = ry - cY(rx). Right stick only.\n")
        h.write("#pragma once\n#include <stdint.h>\n\n")
        h.write("#define ENABLE_RIGHT_STICK_CORRECTION 1\n\n")
        h.write("// DC center offset (int16). Zero these if your in-game deadzone\n")
        h.write("// already swallows the bias.\n")
        h.write("#define RSC_CENTER_X (976)\n#define RSC_CENTER_Y (-128)\n\n")
        h.write("// Diagonal taper: 1.0 = full decouple at all ry. If up-left/down-left\n")
        h.write("// tracking feels over-corrected, lower toward 0 (needs a diagonal\n")
        h.write("// capture to tune properly).\n")
        h.write("#define RSC_TAPER 1.0f\n\n")
        h.write(f"#define RSC_NX {NX}\n")
        h.write("// cY(rx) in normalized units (-1..1), index over rx in [-1, 1]\n")
        h.write("static const float RSC_CY[RSC_NX] = {\n  ")
        for i,v in enumerate(cY):
            h.write(f"{v:+.5f}f,")
            if i%8==7: h.write("\n  ")
        h.write("\n};\n\n")
        h.write(r"""
static inline int16_t rsc_clamp(float v){
    if (v >  32767.0f) return  32767;
    if (v < -32768.0f) return -32768;
    return (int16_t)(v >= 0 ? v + 0.5f : v - 0.5f);
}

// Decouple ONE right-stick sample in place. Left stick must NOT call this.
// Trig-free: one LUT lookup + a subtract. Cheap on RP2040 (no FPU needed).
static inline void correct_right_stick(int16_t *px, int16_t *py){
#if ENABLE_RIGHT_STICK_CORRECTION
    float x = (float)(*px) - (float)RSC_CENTER_X;
    float y = (float)(*py) - (float)RSC_CENTER_Y;

    // index cY by normalized x in [-1, 1]
    float xn = x * (1.0f/32767.0f);
    if (xn < -1.0f) xn = -1.0f; else if (xn > 1.0f) xn = 1.0f;
    float u  = (xn + 1.0f) * 0.5f * (RSC_NX - 1);
    int   i0 = (int)u; if (i0 > RSC_NX-2) i0 = RSC_NX-2; if (i0 < 0) i0 = 0;
    float f  = u - (float)i0;
    float cy = RSC_CY[i0]*(1.0f-f) + RSC_CY[i0+1]*f;   // normalized Y bleed

    y -= cy * 32767.0f * RSC_TAPER;                    // cancel the bulge

    *px = rsc_clamp(x);
    *py = rsc_clamp(y);
#else
    (void)px; (void)py;
#endif
}
""")
    print(f"\nwrote {out}")
    json.dump({"NX":NX,"cY":cY,"pts":pts}, open("bulge_dump.json","w"))

if __name__=="__main__":
    main()