// Auto-generated by fit_bulge.py - right-stick X->Y decoupling
// Cancels the cross-axis bulge: ry' = ry - cY(rx). Right stick only.
#pragma once
#include <stdint.h>

#define ENABLE_RIGHT_STICK_CORRECTION 1

// DC center offset (int16). Zero these if your in-game deadzone
// already swallows the bias.
#define RSC_CENTER_X (976)
#define RSC_CENTER_Y (-128)

// Diagonal taper: 1.0 = full decouple at all ry. If up-left/down-left
// tracking feels over-corrected, lower toward 0 (needs a diagonal
// capture to tune properly).
#define RSC_TAPER 1.0f

#define RSC_NX 33
// cY(rx) in normalized units (-1..1), index over rx in [-1, 1]
static const float RSC_CY[RSC_NX] = {
  +0.04690f,-0.00973f,-0.01950f,-0.00585f,+0.00000f,-0.00195f,-0.00390f,-0.00097f,
  +0.00390f,+0.00634f,+0.00585f,+0.00536f,+0.00682f,+0.00682f,+0.00390f,+0.00097f,
  +0.00000f,+0.00000f,+0.00000f,+0.00000f,+0.00000f,+0.00000f,+0.00000f,+0.00000f,
  +0.00000f,+0.00000f,+0.00000f,+0.00000f,+0.00000f,+0.00000f,+0.00000f,+0.00000f,
  +0.00000f,
};


static inline int16_t rsc_clamp(float v){
    if (v >  32767.0f) return  32767;
    if (v < -32768.0f) return -32768;
    return (int16_t)(v >= 0 ? v + 0.5f : v - 0.5f);
}

// Decouple ONE right-stick sample in place. Left stick must NOT call this.
// Trig-free: one LUT lookup + a subtract. Cheap on RP2040 (no FPU needed).
static inline void correct_right_stick(int16_t *px, int16_t *py){
#if ENABLE_RIGHT_STICK_CORRECTION
    float x = (float)(*px) - (float)RSC_CENTER_X;
    float y = (float)(*py) - (float)RSC_CENTER_Y;

    // index cY by normalized x in [-1, 1]
    float xn = x * (1.0f/32767.0f);
    if (xn < -1.0f) xn = -1.0f; else if (xn > 1.0f) xn = 1.0f;
    float u  = (xn + 1.0f) * 0.5f * (RSC_NX - 1);
    int   i0 = (int)u; if (i0 > RSC_NX-2) i0 = RSC_NX-2; if (i0 < 0) i0 = 0;
    float f  = u - (float)i0;
    float cy = RSC_CY[i0]*(1.0f-f) + RSC_CY[i0+1]*f;   // normalized Y bleed

    y -= cy * 32767.0f * RSC_TAPER;                    // cancel the bulge

    *px = rsc_clamp(x);
    *py = rsc_clamp(y);
#else
    (void)px; (void)py;
#endif
}
