#!/usr/bin/env python3
"""
fit_tau.py - velocity (snapback) compensator fit for the right stick.

The fast/slow captures showed the bulge flips sign and grows with speed -> the
error is proportional to stick VELOCITY, not position. This fits:

    ry_meas(i) ~= Kx * (rx(i) - rx(i-1))  +  cY_slow(rx(i))
                  \___velocity (snapback)___/   \_static positional_/

and emits a header that undoes both, continuously (no direction switching):

    y' = y - Kx*(x - x_prev_smoothed) - cY_slow(x)

Usage: python3 fit_tau.py bulge_fast.ndjson bulge_slow.ndjson [src/stick_correction.h]
"""
import json, sys

def load(path):
    pts=[]
    for line in open(path):
        line=line.strip()
        if not line: continue
        d=json.loads(line)
        if "rx" in d and "ry" in d:
            pts.append((float(d["rx"]), float(d["ry"]), d.get("t")))
    return pts

def median(v):
    v=sorted(v); n=len(v)
    return 0.0 if n==0 else (v[n//2] if n%2 else 0.5*(v[n//2-1]+v[n//2]))

def slow_lut(path, NX):
    if path is None: return [0.0]*NX
    step=2.0/(NX-1); bins={i:[] for i in range(NX)}
    for rx,ry,_ in load(path):
        i=max(0,min(NX-1,int(round((rx+1.0)/step)))); bins[i].append(ry)
    cY=[median(bins[i]) for i in range(NX)]
    mid=(NX-1)//2
    for i in range(mid,NX): cY[i]=0.0
    cY[mid]=0.0
    # fill empties
    known=[i for i in range(NX) if bins[i] or i>=mid]
    for i in range(NX):
        if cY[i] is None: cY[i]=0.0
    return cY

def lerp_lut(lut, xn, NX):
    u=(xn+1.0)*0.5*(NX-1); i=max(0,min(NX-2,int(u))); f=u-i
    return lut[i]*(1-f)+lut[i+1]*f

def main():
    fast=sys.argv[1] if len(sys.argv)>1 else "bulge_fast.ndjson"
    slow=sys.argv[2] if len(sys.argv)>2 and not sys.argv[2].endswith(".h") else None
    out =sys.argv[-1] if sys.argv[-1].endswith(".h") else "stick_correction.h"
    NX=33
    cY=slow_lut(slow, NX)
    pts=load(fast)

    # build regression: residual = ry - cY_slow(rx)  ~  Kx * dx
    Sxx=Sxy=Syy=0.0; n=0
    for k in range(1,len(pts)):
        rx,ry,_=pts[k]; rxp=pts[k-1][0]
        dx=rx-rxp
        if abs(dx)<1e-4: continue          # ignore near-still frames
        r = ry - lerp_lut(cY, rx, NX)
        Sxx+=dx*dx; Sxy+=dx*r; Syy+=r*r; n+=1
    Kx = Sxy/Sxx if Sxx>0 else 0.0
    R2 = (Kx*Sxy)/Syy if Syy>0 else 0.0    # fraction of residual variance explained

    print("="*60)
    print("  VELOCITY (SNAPBACK) COMPENSATOR FIT")
    print("="*60)
    print(f"fast file: {len(pts)} pts, {n} moving | slow LUT: {'yes' if slow else 'none'}")
    print(f"\n  Kx (velocity gain, per normalized sample-step) = {Kx:+.4f}")
    print(f"  variance of the fast bulge explained by velocity = {R2*100:4.1f}%")
    print(f"  -> firmware correction at full flick speed (dx~0.15): {Kx*0.15:+.3f} of Y\n")
    if R2 < 0.4:
        print("  WARNING: velocity explains <40% of the bulge. The snapback model may")
        print("  be wrong or the capture noisy - inspect before trusting Kx.")
    else:
        print("  velocity dominates -> snapback model confirmed; compensator written.")

    # convert Kx to int16-domain gain: y_int -= Kx * dx_int16  (units already consistent)
    with open(out,"w") as h:
        h.write("// Auto-generated by fit_tau.py - right-stick snapback compensator\n")
        h.write("// y' = y - Kx*(x - x_prev_smoothed) - cY_slow(x). Continuous, no switching.\n")
        h.write("#pragma once\n#include <stdint.h>\n\n")
        h.write("#define ENABLE_RIGHT_STICK_CORRECTION 1\n")
        h.write("#define RSC_CENTER_X (976)\n#define RSC_CENTER_Y (-128)\n\n")
        h.write(f"#define RSC_KX        {Kx:+.5f}f   // velocity lead gain (measured)\n")
        h.write("#define RSC_VX_SMOOTH 0.40f     // EMA on dx; lower = smoother, more lag\n")
        h.write("#define RSC_MAX_CORR  9000      // clamp |velocity correction| (int16) - noise guard\n")
        h.write(f"#define RSC_NX {NX}\n")
        h.write("// static positional residual cY_slow(rx), from the SLOW capture\n")
        h.write("static const float RSC_CY[RSC_NX] = {\n  ")
        for i,v in enumerate(cY):
            h.write(f"{v:+.5f}f,"); 
            if i%8==7: h.write("\n  ")
        h.write("\n};\n\n")
        h.write(r"""
static inline int16_t rsc_clamp(float v){
    if (v >  32767.0f) return  32767;
    if (v < -32768.0f) return -32768;
    return (int16_t)(v >= 0 ? v + 0.5f : v - 0.5f);
}

// Snapback compensator. One previous-sample state; one caller (process_xinput).
static inline void correct_right_stick(int16_t *px, int16_t *py){
#if ENABLE_RIGHT_STICK_CORRECTION
    static int16_t x_prev = 0;
    static float   vx     = 0.0f;     // smoothed per-sample dx
    static int     primed = 0;

    int16_t xi = (int16_t)(*px - RSC_CENTER_X);
    float   y  = (float)(*py) - (float)RSC_CENTER_Y;

    int dx = (int)xi - (int)x_prev;
    x_prev = xi;
    if (!primed){ primed = 1; dx = 0; }          // no spike on first report
    vx += RSC_VX_SMOOTH * ((float)dx - vx);       // smooth the velocity

    // velocity (snapback) lead - the dominant, speed-driven error
    float vcorr = RSC_KX * vx;
    if (vcorr >  (float)RSC_MAX_CORR) vcorr =  (float)RSC_MAX_CORR;
    if (vcorr < -(float)RSC_MAX_CORR) vcorr = -(float)RSC_MAX_CORR;
    y -= vcorr;

    // static positional residual (from the slow capture)
    float xn = (float)xi * (1.0f/32767.0f);
    if (xn < -1.0f) xn = -1.0f; else if (xn > 1.0f) xn = 1.0f;
    float u  = (xn + 1.0f) * 0.5f * (RSC_NX - 1);
    int   i0 = (int)u; if (i0 > RSC_NX-2) i0 = RSC_NX-2; if (i0 < 0) i0 = 0;
    float f  = u - (float)i0;
    y -= (RSC_CY[i0]*(1.0f-f) + RSC_CY[i0+1]*f) * 32767.0f;

    *px = rsc_clamp((float)xi);
    *py = rsc_clamp(y);
#else
    (void)px; (void)py;
#endif
}
""")
    print(f"  wrote {out}")

if __name__=="__main__":
    main()